apiVersion: v1
kind: ConfigMap
metadata:
  name: part-1
data:
  # property-like keys; each key maps to a simple value
  backend_url: "http://localhost:8000"
  data_file: "special_names.csv"
  sleep_duration: "10"
